#################################################################################
#                                 PRODUCTION                                    #
#################################################################################

[deployment.ethereum-mainnet]
name = "Ethereum Mainnet"
id = 1
etherscan-url = "https://etherscan.io/"
version = "v0.10.0"

# Accounts
admin = "0x0000000000000000000000000000000000000000"

# Contracts
verifier = "0x8EaB2D97Dfce405A1692a21b3ff3A172d593D319"
set-verifier = "0x0000000000000000000000000000000000000000"
boundless-market = "0x0000000000000000000000000000000000000000"
boundless-market-impl = "0x0000000000000000000000000000000000000000"
boundless-market-old-impl = "0x0000000000000000000000000000000000000000"
collateral-token = "0x0000000000000000000000000000000000000000"

# Guests info
deployment-commit = "0x0000000000000000000000000000000000000000" # v0.10.0 main
assessor-image-id = "0x0000000000000000000000000000000000000000000000000000000000000000"
assessor-guest-url = "0x0000000000000000000000000000000000000000"
deprecated-assessor-duration = 0  # 5 days

# PoVW contracts
povw-accounting = "0x319bd4050b2170a7aE3Ead3E6d5AB8a5c7cFBDF8"
povw-accounting-impl = "0xfb2187436fD8e266E4F18cBCe9aAFbDbB796e67C"
povw-accounting-old-impl = "0x0000000000000000000000000000000000000000"
povw-accounting-admin = "0x3886eeaf95aa2bdddf0c924925e290291f70447f"
povw-accounting-deployment-commit = "0556e6b61"
povw-mint = "0xBFCE7c2d5e7EdDEab71B3eeED770713c8b755397"
povw-mint-impl = "0x569D48052d59dC4aAC86098fE8db43D0E514f59B"
povw-mint-old-impl = "0x0000000000000000000000000000000000000000"
povw-mint-admin = "0x3886eeaf95aa2bdddf0c924925e290291f70447f"
povw-mint-deployment-commit = "0556e6b61"

# PoVW image IDs
povw-log-updater-id = "0x004b225edce73d0fd399993c14bea083a08bc346eacd68a644946179ebc4818f"
povw-mint-calculator-id = "0x6a12be89391574535f998faf60bc4993b52c42f195d1482896b8154109db76bf"

# ZKC contracts
zkc = "0x000006c2A22ff4A44ff1f5d0F2ed65F781F55555"
vezkc = "0xE8Ae8eE8ffa57F6a79B6Cbe06BAFc0b05F3ffbf4"

[deployment.base-mainnet]
name = "Base Mainnet"
id = 8453
etherscan-url = "https://basescan.org/"
version = "v1.0.0" # dd0a257e main

# Boundless Market admins
admin = "0x0000000000000000000000000000000000000000"
admin-2 = "0xb04d1a222789a76e74168a919b43b20f66e24f0b"

# Contracts
verifier = "0x0b144e07a0826182b6b59788c34b32bfa86fb711"
set-verifier = "0x1Ab08498CfF17b9723ED67143A050c8E8c2e3104"
# deployed at block 31134603
boundless-market = "0xfd152dadc5183870710fe54f939eae3ab9f0fe82"
boundless-market-impl = "0x8d3D36400d0a8Cf7cF217D28D366a0189F0850B6"
boundless-market-old-impl = "0x0786bf3387db42475f56e15a507147a716d79b35"
collateral-token = "0xAA61bB7777bD01B684347961918f1E07fBbCe7CF"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x03831182a226b5f5a4d358704a9f9d0bcd4dc48e6e577dc7db84d94892024938"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 0  # 5 days
boundless-market-deployment-commit = "dd0a257e"

[deployment.ethereum-sepolia]
name = "Ethereum Sepolia [prod]"
id = 11155111
etherscan-url = "https://sepolia.etherscan.io/"
version = "v1.0.0" # dd0a257e main

# Boundless Market admins
admin = "0x0000000000000000000000000000000000000000"
admin-2 = "0xb04d1a222789a76e74168a919b43b20f66e24f0b"

# Contracts
verifier = "0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187"
set-verifier = "0xcb9D14347b1e816831ECeE46EC199144F360B55c"
# deployed at block 8476627
boundless-market = "0xc211b581cb62e3a6d396a592bab34979e1bbba7d"
boundless-market-impl = "0x13eDcF55BE5af2bF367e235fD9B60Ca5686A79df"
boundless-market-old-impl = "0x9ef96f69881d54ea521cbbdec63617af0e484aa3"
boundless-market-deployment-commit = "dd0a257e"
collateral-token = "0xb4FC69A452D09D2662BD8C3B5BB756902260aE28"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x03831182a226b5f5a4d358704a9f9d0bcd4dc48e6e577dc7db84d94892024938"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 432000  # 5 days

# PoVW contracts
povw-accounting = "0xC5E956732F4bA6B1973a859Cf382244db6e84D0b"
povw-accounting-impl = "0x3BDFC7Dcef6e93AF23aEBC61C9f0Cda8D9aD7CBa"
povw-accounting-old-impl = "0x0000000000000000000000000000000000000000"
povw-accounting-admin = "0xB04D1a222789A76E74168a919b43b20F66e24f0b"
povw-accounting-deployment-commit = "8affce9b4"
povw-mint = "0xc98218AafE225035a34795Bf4f6777b7d541E326"
povw-mint-impl = "0x86d54CbD084674FA86c57A98eD9b8A5BA4B16a17"
povw-mint-old-impl = "0x0000000000000000000000000000000000000000"
povw-mint-admin = "0xB04D1a222789A76E74168a919b43b20F66e24f0b"
povw-mint-deployment-commit = "8affce9b4"

# PoVW image IDs
povw-log-updater-id = "0x004b225edce73d0fd399993c14bea083a08bc346eacd68a644946179ebc4818f"
povw-mint-calculator-id = "0x6a12be89391574535f998faf60bc4993b52c42f195d1482896b8154109db76bf"

# ZKC contracts
zkc = "0xb4FC69A452D09D2662BD8C3B5BB756902260aE28"
vezkc = "0xc23340732038ca6C5765763180E81B395d2e9cCA"

[deployment.base-sepolia]
name = "Base Sepolia [prod]"
id = 84532
etherscan-url = "https://sepolia.basescan.org/"
version = "v1.0.0" # dd0a257e main

# Boundless Market admins
admin = "0x0000000000000000000000000000000000000000"
admin-2 = "0xb04d1a222789a76e74168a919b43b20f66e24f0b"

# Contracts
verifier = "0x0b144e07a0826182b6b59788c34b32bfa86fb711"
set-verifier = "0x1Ab08498CfF17b9723ED67143A050c8E8c2e3104"
# deployed at block 26646012
boundless-market = "0x56da3786061c82214d18e634d2817e86ad42d7ce"
boundless-market-impl = "0x7d4bb6295e56ba3e93f51f44598310539cd783a2"
boundless-market-old-impl = "0x3966c33ee391c6c16a874ef4609eea875424d52b"
boundless-market-deployment-commit = "dd0a257e"
collateral-token = "0x8d4dA4b7938471A919B08F941461b2ed1679d7bb"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x03831182a226b5f5a4d358704a9f9d0bcd4dc48e6e577dc7db84d94892024938"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 432000  # 5 days

#################################################################################
#                                  STAGING                                      #
#################################################################################

[deployment.ethereum-sepolia-staging]
name = "Ethereum Sepolia [staging]"
id = 11155111
etherscan-url = "https://sepolia.etherscan.io/"
version = "v0.14.0" # 1353e11c main

# Boundless Market admins
admin = "0x0000000000000000000000000000000000000000"

# Contracts
verifier = "0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187"
set-verifier = "0xcb9D14347b1e816831ECeE46EC199144F360B55c"
boundless-market = "0x0000000000000000000000000000000000000000"
boundless-market-impl = "0x0000000000000000000000000000000000000000"
boundless-market-old-impl = "0x0000000000000000000000000000000000000000"
collateral-token = "0x0000000000000000000000000000000000000000"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x03831182a226b5f5a4d358704a9f9d0bcd4dc48e6e577dc7db84d94892024938"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 432000  # 5 days

# PoVW contracts
povw-accounting-admin = "0xB04D1a222789A76E74168a919b43b20F66e24f0b"
povw-mint-admin = "0xB04D1a222789A76E74168a919b43b20F66e24f0b"
povw-accounting = "0x129aEAB812d77c102ff1AD9D76DfB55FaAE4b8D3"
povw-accounting-impl = "0x12a4bf74f23343badabce899653c072cdccf1f75"
povw-accounting-old-impl = "0x7959bc1a7a8dfe0b031964115e5e2eda98a95d91"
povw-mint = "0x8C2A4A28116Ed8b8Fe559BC53e30B6a056C5d3C9"
povw-mint-impl = "0x43952737A52eD2ccc8C148884993120F2F94Fc98"
povw-mint-old-impl = "0x0000000000000000000000000000000000000000"
povw-log-updater-id = "0x004b225edce73d0fd399993c14bea083a08bc346eacd68a644946179ebc4818f"
povw-mint-calculator-id = "0x6a12be89391574535f998faf60bc4993b52c42f195d1482896b8154109db76bf"
povw-accounting-deployment-commit = "8abd7aa97"
povw-mint-deployment-commit = "8affce9b4"

# ZKC contracts
zkc = "0x99A52662b576f4b2D4FFBc4504331A624a7b2846"
vezkc = "0xB7c63161DA06eC56840465308e24C70dF65ABC56"

[deployment.base-sepolia-staging]
name = "Base Sepolia [staging]"
id = 84532
etherscan-url = "https://sepolia.basescan.org/"
version = "v1.0.0" # dd0a257e main

# Boundless Market admins
admin = "0x210173cEfF92264c565229e0c9CE02DF4C1Ba5aD"
admin-2 = "0xb04d1a222789a76e74168a919b43b20f66e24f0b"

# Contracts
verifier = "0x0b144e07a0826182b6b59788c34b32bfa86fb711"
set-verifier = "0x1Ab08498CfF17b9723ED67143A050c8E8c2e3104"
# deployed at block 26370829
boundless-market = "0x7abb16522f4599481361d318b765af988bfcca8e"
boundless-market-impl = "a77e62126fcae0df84f58b072cd2b3c3e5b6c6ae"
boundless-market-old-impl = "0xec7562b21409bf9085ad70964211a3db628d75eb"
boundless-market-deployment-commit = "dd0a257e"
collateral-token = "0xCBA5Fd30105984125395c18B6E6b1bf603408629"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x03831182a226b5f5a4d358704a9f9d0bcd4dc48e6e577dc7db84d94892024938"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 432000  # 5 days

#################################################################################
#                               QUICK EPOCH                                     #
#################################################################################

[deployment.ethereum-sepolia-quick-epoch]
name = "Ethereum Sepolia [Quick Epoch]"
id = 11155111
etherscan-url = "https://sepolia.etherscan.io/"
version = "v0.10.0" # 1ba84b6c1914fda4937392ccb54a82c8e91d4940

# Boundless Market admins
admin = "0x08C35D3ADD5b4e914a1742f08bf00e72A85Cbe90"

# Contracts
verifier = "0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187"
set-verifier = "0xcb9D14347b1e816831ECeE46EC199144F360B55c"
# deployed at block 8430932
boundless-market = "0x0000000000000000000000000000000000000000"
boundless-market-impl = "0x0000000000000000000000000000000000000000"
boundless-market-old-impl = "0x0000000000000000000000000000000000000000"
collateral-token = "0x03f177Bd8A0CF725c29945C0a0434897A4a16628"

# Guests info
deployment-commit = "918934a418b00cce8524caf7a061e058cc945451" # v0.10.0 main
assessor-image-id = "0x0000000000000000000000000000000000000000000000000000000000000000"
assessor-guest-url = "https://gateway.beboundless.cloud/ipfs/bafybeibf7u5cltvkqg3yduo3yycrlxruoig4ew5pcvljx2zjua3gnypv2q"
deprecated-assessor-duration = 259200  # 3 days

# PoVW contracts
povw-accounting-admin = "0x48268bE6235A23eb7b67356469362869D5d0293f"
povw-mint-admin = "0x48268bE6235A23eb7b67356469362869D5d0293f"
povw-accounting = "0x705e261854555dEB5Ab125cE4f722f78C0074bE2"
povw-accounting-impl = "0xedba590f7d6252cf259247396036f22def7b40dd"
povw-accounting-old-impl = "0xa33dec083f4aff0a7c99cb279562ba81c792286c"
povw-mint = "0x35066ca433583441F5Db084775B9D065958205E7"
povw-mint-impl = "0x8a7ef7d77f372642d9a360bd6a326819f634a7a0"
povw-mint-old-impl = "0x3a41b19cd02e58aabaef199e61bd27602333dcf2"
povw-log-updater-id = "0x004b225edce73d0fd399993c14bea083a08bc346eacd68a644946179ebc4818f"
povw-mint-calculator-id = "0x6a12be89391574535f998faf60bc4993b52c42f195d1482896b8154109db76bf"
povw-accounting-deployment-commit = "61ab81e65"
povw-mint-deployment-commit = "61ab81e65"

# ZKC contracts
zkc = "0x03f177Bd8A0CF725c29945C0a0434897A4a16628"
vezkc = "0x645D173cEe5F16aDA0c7C6aDb66ed489Df7EB7Fc"

#################################################################################
#                              DEVELOPMENT                                      #
#################################################################################

[deployment.anvil]
name = "Anvil"
id = 31337
etherscan-url = ""

# Boundless Market admins
admin = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

# Contracts
verifier = "0x0000000000000000000000000000000000000000"
set-verifier = "0x0000000000000000000000000000000000000000"
boundless-market = "0x0000000000000000000000000000000000000000"
boundless-market-impl = "0x0000000000000000000000000000000000000000"
boundless-market-old-impl = "0x0000000000000000000000000000000000000000"
collateral-token = "0x0000000000000000000000000000000000000000"

# Guests info
deployment-commit = "1353e11c" # v0.14.0 main
assessor-image-id = "0x661051a91ef01febc96e11f38280281a08cfeeb37fb3a2d984f4a8f703965cc3"
assessor-guest-url = "https://staging-signal-artifacts.beboundless.xyz/v3/assessor/assessor_guest.bin"
deprecated-assessor-duration = 0

# PoVW contracts
povw-accounting = "0xf52C066Ff41409c49126cfd6be8a540a216a63e2"
povw-accounting-impl = "0x3c80D582E8019ed0A9bcc69F98781d90Fb3eAc4a"
povw-accounting-old-impl = "0x0000000000000000000000000000000000000000"
povw-accounting-admin = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
povw-accounting-deployment-commit = "unknown"
povw-mint = "0x4734C8f39548B124b0115f4927E6897765ee05C2"
povw-mint-impl = "0xa028eB36CBBb07d0Ba894d686bD640A0F723f6F8"
povw-mint-old-impl = "0x0000000000000000000000000000000000000000"
povw-mint-admin = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
povw-mint-deployment-commit = "unknown"

# PoVW image IDs
povw-log-updater-id = "0x1234567890123456789012345678901234567890123456789012345678901234"
povw-mint-calculator-id = "0x5678901234567890123456789012345678901234567890123456789012345678"

# ZKC contracts (could be mocks in dev mode)
zkc = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
vezkc = "0x0165878A594ca255338adfa4d48449f69242Eb8F"
